### ISSUE TITLE
Advanced log: Queuing a QSL for Bureau shows up in the Clublog column until refresh.

### ISSUE THREAD

**Issue by toco** [wavelog/wavelog#1008]
**Describe the bug**
When in the advanced logbook view, using the "Queue Bureau" action with selected log entries updates Clublog instead of QSL column. After hitting "Search" the state is updated in the right column.

**Version Information**
- Wavelog:          1.7
- DF instance

**Steps to Reproduce**
1. Go to Logbook > Advanced
2. Select a QSO.
3. Click on "Actions"
4. Click on "Queue Bureau"

**Expected Behavior**
I'd expect the QSL status in the QSL column to be updated.

**Observed Behaviour**
The QSL status is updated in the Clublog column instead of the QSL column.

**Notes**
Clicking "Search" resolves the state mismatch, this appears to be a temporary issue with the immediate UI update and not an issue that is persisted to the database. 

**Screenshots**

https://github.com/user-attachments/assets/388b894f-16f7-4326-b057-c41231250fca

(Sorry for the bad resolution, GitHub upload limit…)

**Desktop Information:**
- OS: macOS 14.6.1 (23G93)
- Browser: Safari 
- Version: Version 17.6 (19618.3.11.11.5)

**Comment by AndreasK79** [comment]
Hi, thanks for reporting. This bug is already fixed. I would advice you to upgrade to the latest version.
