### ISSUE TITLE
LoTW Tooltip shows up twice - Frontend Bug

### ISSUE THREAD

**Issue by HB9HIL** [wavelog/wavelog#1030]
I’ve noticed a small issue that occurs when I start logging a QSO (which I often do just to gather information about a callsign without actually completing the log) and leave the browser tab open. When I later begin logging a QSO for a different callsign and hover the mouse pointer over the LoTW image, I sometimes see two black popups, or occasionally just one, showing LoTW data from the previous callsign I had started logging but didn’t finish. It seems that the wrong LoTW image is also displayed in these cases.

Thank you for everything you've done so far! This is just a small observation that I hope can help improve the experience even further.

![image](https://github.com/user-attachments/assets/dcba6e79-dc3f-49a9-9051-3505c0cbd699)

Browser used Mozilla Firefox 130.0.1 (64-bit) on Windoze

_Originally posted by @besynnerlig in https://github.com/wavelog/wavelog/issues/978#issuecomment-2386844417_

**Comment by HB9HIL** [comment]
I was not able to reproduce this :( it's difficult if it happens just "sometimes" and just in Firefox..

**Comment by besynnerlig** [comment]
I can share a video showing it. Anyway, this doesn't bother me a lot. It might not be worth investigating, I don't know. 

https://github.com/user-attachments/assets/9ff1fc41-ed5a-45c5-93d4-9042ad062ecf

**Comment by phl0** [comment]
Cannot reproduce either ...

**Comment by HB9HIL** [comment]
<img width="381" alt="image" src="https://github.com/user-attachments/assets/d95b8916-0b66-45ac-8d32-c861fabfc978">
got it

investigating

**Comment by HB9HIL** [comment]
<img width="723" alt="image" src="https://github.com/user-attachments/assets/9dd23646-e893-4d71-bc0d-5b429425c136">

for documentation. will investigate later this day

**Comment by HB9HIL** [comment]
fixed
