### ISSUE TITLE
button style wrong

### ISSUE THREAD

**Issue by hellofinch** [wavelog/wavelog#1080]
**This is for reporting bugs with the code, if this issue is regarding setting up on your local server please use the discussions area**

**Describe the bug**
In mode page, the button clicked but the color doesn't change.
And the translation missed.

![image](https://github.com/user-attachments/assets/7a453253-417a-47ec-ab52-8f6253964143)

**Comment by AndreasK79** [comment]
Fix here https://github.com/wavelog/wavelog/pull/1083.

Thanks for reporting.

**Comment by HB9HIL** [comment]
@hellofinch 

I added the translatables to the PR aswell. After merge the strings are translatable in weblate -> https://translate.wavelog.org

**Comment by hellofinch** [comment]
I believe this is a display issue, and there is no problem with the translation.
I see something not translated into Chinese. I will contribute some translations in weblate. :)

**Comment by HB9HIL** [comment]
> I believe this is a display issue, and there is no problem with the translation. I see something not translated into Chinese. I will contribute some translations in weblate. :)

some of the javascript things weren't translatable yet. this is fixed now. 

small hint: weblate is offline from now on for approx. 1 hour (16th oct 2024 0700z to 0800z)
