### ISSUE TITLE
translation string miss

### ISSUE THREAD

**Issue by hellofinch** [wavelog/wavelog#1091]
Hello, everyone.
There are some strings missing.
I see 100% percent completed in weblate. As you can see, some string shows in English.
Does weblate miss something or this string came from [Codeigniter](https://www.codeigniter.com/docs)?
:)
![image](https://github.com/user-attachments/assets/1c5154e2-d0bc-4ff4-b553-fc661df7f30b)
![image](https://github.com/user-attachments/assets/29855f96-8f77-42c2-bae8-abe7caf16415)

**Comment by HB9HIL** [comment]
Hello @hellofinch 

you are right. Not all strings are prepared for translation. Javascript to Gettext is a manual work which needs quite some effort. You will see that the translation appear from time to time :) 


It's not a bug, just not coded yet 😀
