### ISSUE TITLE
eQSL: Standard-QSLMSG will not be attached when QSO is created by API

### ISSUE THREAD

**Issue by 205er** [wavelog/wavelog#1094]
**Describe the bug**
QSO are created by WSJT-X using the API of Wavelog. The location dependent Standard-QSLMSG, which is uploaded to eQSL, is not attached to these QSO. (field is empty) If you edit the QSO afterwards, the msg gets attached.

**Version Information**
- Wavelog:          1.8.7

**Expected Behavior**
Standard-QSLMSG should be included in all QSO, even for API-created QSO.

**Comment by HB9HIL** [comment]
fixed and will be released soon

**Comment by 205er** [comment]
Thanks!
