### ISSUE TITLE
Missing button "Export SELECTED QSOs to ADIF-file" in "QSL Queue" view

### ISSUE THREAD

**Issue by m0urs** [wavelog/wavelog#1110]
**What Feature is Missing?**

If you are in the QSO Queue view, you currently have the following buttons available:

![grafik](https://github.com/user-attachments/assets/a46f9f9b-d37b-47e3-8553-d7af7779b4f3)

I am missing a button "Export SELECTED QSOs to ADIF-file". I also miss the button "Mark SELECTED QSos as sent" but maybe the existing button "Mark selected QSOs as print" does exactly that and has just another name?

Maybe we also can change all references to "Print/Printed" in that view as it is not only related to print QSLs (the menu item is also no longer called "Print QSLs" but "QSL Queue" ....

**Why is This Feature Important?**

As I have QSOs which should be answered directly and other QSOs which should be answered via Bureau I do not always want to work with ALL QSOs in that list but just select some of them (e.g. only the Burea requests) and want to have them exported and marked as sent after I finished the requests.

**Is This Feature Personal or Beneficial to Others as Well?**

I think othes would also have the same issue and would like to have that added.

**Comment by HB9HIL** [comment]
This is implemented with #1123
