### ISSUE TITLE
Show eqsl status in popup window (displayContacts) when clicking on today received eqsls

### ISSUE THREAD

**Issue by winnieXY** [wavelog/wavelog#1119]
**What Feature is Missing?**
When clicking on  todays received eqsls another window opens which displays the today confirmed qsos:

![grafik](https://github.com/user-attachments/assets/684f4515-db3f-4461-9449-5294197b4a78)

However, within this window it's impossible to see the eqsl status or view the received cards as the eqsl row is missing:
![grafik](https://github.com/user-attachments/assets/3bbe8d2f-b82e-46ae-a0c6-93cb94b2565f)

(Obviously I got no confirmed eqsls today so far ;-))

**Why is This Feature Important?**
Important is the wrong word - nice would be the better one. :-) to get a short overview over the received cards. 

**Is This Feature Personal or Beneficial to Others as Well?**
I guess this will be beneficial also for others.

**Comment by xyz667** [comment]
eQSL is showing as a table header for me in that popup (but no Clublog as I don't use it).
Can't confirm content of that column as I don't have confirmations today either. ;-)

**Comment by int2001** [comment]
i don't get the point here.
if there's no confirmation via eQSL "today", the popup-table is empty.

we can disable the link, if the eQSL-Counter is Zero? Is this the issue?!

**Comment by int2001** [comment]
PS: We discussed internally a bit with an enabled "glass ball".
Do you mean the COLUMN eQSL which ist missing IF there are eQSL's today?

if: pse go to settings and add eQSL as a default QSL-Method.

**Comment by winnieXY** [comment]
@int2001 : sorry for being unclear. Yes. This was the intented meaning. Thanks for the hint.
