### ISSUE TITLE
On mobile, multiple menus can be opened and overlays render over top of eachother

### ISSUE THREAD

**Issue by gx1400** [wavelog/wavelog#1157]
**Describe the bug**
On Mobile (Android, Mozilla Firefox), menu expanders open and overlay on top of on another

**Version Information**
We need some information about your versions. You can get all Information in the Admin > Debug Menu
- OS:               Ubuntu 24.04
- PHP:              8.3
- MySQL/MariaDB:    11.3.2
- Wavelog:          1.8.8

running from latest docker release as of Nov 3 2024

```
Server Software | Apache/2.4.62 (Debian)
PHP Version | 8.3.12 OK
MySQL Version | 11.3.2-MariaDB-1:11.3.2+maria~ubu2204
Codeigniter Version | 3.2.0-dev
```

**Steps to Reproduce**
1. Login
2. Click on hamburger menu
3. Click on Tools menu,
4. With tools menu still open, click on QSO menu
5. With both menus above open, click on Logbook

**Expected Behavior**
When tools menu is open and QSO menu is clicked on, tools menu should close
When QSO menu is open and logbook menu is clicked, QSO menu should close

**Screenshots**
![Screenshot_20241103-203026](https://github.com/user-attachments/assets/b5e0e1fe-ff33-40d6-bd3a-544d3213344c)

**Smartphone Information:**
- Device:           Google Pixel 7
- OS:               Android 15
- Browser:          Mozilla Firefox mobile
- Version:          132.0

**Additional Context**
Provide any other relevant context about the problem.

**Comment by HB9HIL** [comment]
Duplicate to #691
