### ISSUE TITLE
Create Logbook Filter for "Where Grid is empty"

### ISSUE THREAD

**Issue by HochdruckHummer** [wavelog/wavelog#1174]
It's currently not possible to search for fields that are empty. (Or I didn't find out how to do that).

Please provide a filter to show only QSOs with missing grid. That way I would be able to batch select all search results for Callbook update.

**Comment by dg9vh** [comment]
Hi,
![image](https://github.com/user-attachments/assets/de8af2a6-9b52-4fbb-8193-dcc4d03854d4)
Using advanced search would bring you to your target.

**Comment by HochdruckHummer** [comment]
I'm sorry... How do I get to advanced search?

**Comment by HochdruckHummer** [comment]
This small moment of joy "Yay, this function is already given, I'm so happy!" to "Naaah, doesn't work".... :)

**Comment by dg9vh** [comment]
but for locating them, you should use following:
![image](https://github.com/user-attachments/assets/29b9aaa8-f13c-4092-b1c4-2b133f5552ad)
then you know them :-) but how to actualize them in batch from qrz.com is open - so this could be a real feature request. @HB9HIL @phl0

**Comment by dg9vh** [comment]
We just need a mass editing function (like in advanced log) here in advanced search based on the search result.

**Comment by HB9HIL** [comment]
It's probably easier to add this "is empty" filter in Logbook Advanced then add Batch Edit/Update From Callbook in the Advanced Search.

**Comment by dg9vh** [comment]
Well, yes... correct :-) but in advanced log you do not get all "in one query"... only up to 5000

**Comment by AndreasK79** [comment]
As an empty filter is a good suggestion, I will add that. Probably with a dropdown, so you can choose which column.

**Comment by AndreasK79** [comment]
Added PR here #1220. With this change, you can search for empty values where the filter is a textbox.

**Comment by AndreasK79** [comment]
Merged into dev for those wanting to test.
