### ISSUE TITLE
RST and Exchange are not correctly parsed after update from callbook

### ISSUE THREAD

**Issue by dg9vh** [wavelog/wavelog#1181]
**This is for reporting bugs with the code, if this issue is regarding setting up on your local server please use the discussions area**

**Describe the bug**
After updating a contest-qso in advanced logbook from callbook, the report and exchange (here serial) are not parsed and rendered correctly. After reloading the page all is ok again.

**Version Information**
We need some information about your versions. You can get all Information in the Admin > Debug Menu
- OS:               DARC Wavelog
- PHP:              DARC Wavelog
- MySQL/MariaDB:    DARC Wavelog
- Wavelog:          DARC Wavelog

**Steps to Reproduce**
1. Mark a contest qso with serial-exchange in advanced logbook
2. Click on 'update from callbook'
3. See error

**Expected Behavior**
Should be "normal"

**Screenshots**
![image](https://github.com/user-attachments/assets/b5067522-2310-455b-ae02-7dfdd6640f21)

**Desktop Information:**
- OS:               Debian 12
- Browser:          Chrome
- Version:          Version 130.0.6723.116 (Offizieller Build) (64-Bit)

**Comment by AndreasK79** [comment]
Thanks for the report. It's fixed in the dev branch😊
