### ISSUE TITLE
Reduce DXCC summary to filled fields and make a red frame around the cell depending on the QRG and Mode

### ISSUE THREAD

**Issue by dg2ron** [wavelog/wavelog#1188]
Is it possible to reduce the summary to the filled fields? This simplifies the overview.

![image](https://github.com/user-attachments/assets/cd05dc81-b187-444a-b10f-0108f928d4fa)

to

![image](https://github.com/user-attachments/assets/bf20f811-73de-4cef-9ca2-9800c3048155)

and make a red frame around the cell depending on the QRG and mode

![image](https://github.com/user-attachments/assets/9c0c8aa4-44d7-4f15-bd46-96a33816ae94)

**Comment by HB9HIL** [comment]
Enhancement in the PR

**Comment by HB9HIL** [comment]
merged and will be available soon for you @dg2ron

**Comment by int2001** [comment]
soon is now ;)
