### ISSUE TITLE
Creating QSL-Labels

### ISSUE THREAD

**Issue by dg9vh** [wavelog/wavelog#123]
**Describe the bug**
When creating a QSL label there are two fields to set width and height of the used label. this could be left blank without any error-message. The resulting label could be used for generating labels on the printer but the labels are very unusable :-)

There should be mandatory fields and error messages if there is no input.

**Comment by int2001** [comment]
totally agree. i'm working on it.

**Comment by int2001** [comment]
#126 will solve it.

**Comment by int2001** [comment]
can u cnfm and close the issue afterwards (if everything is okay), @dg9vh ?

**Comment by dg9vh** [comment]
Works as expected... closed.
