### ISSUE TITLE
Wavelog - baseurl problem.

### ISSUE THREAD

**Issue by atimias** [wavelog/wavelog#1230]
**This is for reporting bugs with the code, if this issue is regarding setting up on your local server please use the discussions area**

**Describe the bug**
Baseurl rewrites address what makes it hard to work both by subdomain (using Nginx Proxy Manager) and also by local IP address.

**Version Information**
We need some information about your versions. You can get all Information in the Admin > Debug Menu
- OS: Debian 12
- PHP: 8.2.24
- MariaDB: 11.3
- Wavelog: 1.8.8

**Steps to Reproduce**
1. Build wavelog from official docker image.
2. Set baseurl to 192.168.1.X
3. Configure NPM proxy_host to reach 192.168.1.X:8086
4. When using subdomain.domain.tld the url is being rewritten. Baseurl has to be set to subdomain.domain.tld, but then - won't work by local IP, or breaks css and so on.

**Expected Behavior**
I'd like to make an one instance to work on private and public subdomain without tinkering.

**Screenshots**

**Desktop Information:**
- OS: Debian 12
- Browser: Chrome/Firefox
- Version: current

**Additional Context**
Maybe I am overthinking the problem. Not so great experience in Nginx Proxy Manager.
Looking forward for help.

Thank you!

**Comment by HB9HIL** [comment]
Hello @atimias 

The `baseurl` is part if the Codeigniter Framework. We unfortunately can not simpley override this. 

I'm sorry. 

If you want to reach your installation also in a local network without having access from outside you could add a local DNS override which points to the NGPM. But this is not Wavelog and not a bug.
