### ISSUE TITLE
Timeline Query times out

### ISSUE THREAD

**Issue by jwussler** [wavelog/wavelog#1238]
I am on the dev branch 1.8.8

When i run a query under analytics and select all and use the check mark for just lotw confrontations the page turns white and times out

![image](https://github.com/user-attachments/assets/68659dec-f71c-4e7b-b27e-44411e27fe4c)

I can run the query per band and it works fine. Just not when everything is selected to all

Joe
WAØO

**Comment by int2001** [comment]
Hi @jwussler ,
can you provide some more information?

at first pse take a look at the JS-Console (F12) and network. Would be great if you can share the result of the call to `/timeline` when submit was pressed.

at 2nd: can you enable logging and show us whats in the application-log? (`/application/logs/`)

**Comment by jwussler** [comment]
here the log file 

<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>

ERROR - 2024-11-21 07:27:19 --> Severity: error --> Exception: FUNCTION wavelog.0and does not exist /var/www/html/system/database/drivers/mysqli/mysqli_driver.php 301


![image](https://github.com/user-attachments/assets/a9551641-a418-4d23-badf-fb55823cfe2d)

**Comment by int2001** [comment]
huh? That 0and thing is very strange.
can you provide an ADIF-Export? You can see my eMail-Adress at qrz.com

Idea: You imported an ADIF which was created with another tool. And there are Bands within that adif, which do not exist. but just an idea.

73 de DJ7NT

**Comment by int2001** [comment]
tnx for the File.
Found the bug - it's not your ADIF which causes the problem.
i am going to fix it

**Comment by int2001** [comment]
should be fixed now.

are u using docker (in that case i've to rebuild the dev-image - takes about 10minutes)?
otherwise simply pull latest dev

**Comment by jwussler** [comment]
I am not on docket
