### ISSUE TITLE
Mode Changes Unexpectedly When QSYing to Call Sign

### ISSUE THREAD

**Issue by spREGR** [wavelog/wavelog#1262]
Describe the bug
When I click on a call sign in the Bandlist section, the radio QSYs (changes frequency) to the desired call sign, but the mode changes from CW-U (Continuous Wave Upper) to USB (Upper Sideband) unexpectedly.

Version Information

    OS: [Debian 12]
    PHP: [8.3.12]
    MySQL/MariaDB: [11.3.2-MariaDB-1:11.3.2+maria~ubu2204]
    Wavelog: [1.8.8]

Steps to Reproduce

    Go to Bandlist in Wavelog
    Click on a desired call sign
    The radio QSYs to the selected call sign
    Observe that the mode switches from CW-U to USB

Expected Behavior
I expect the radio to QSY to the selected call sign, but the mode should remain as CW-U instead of changing to USB.

Radio: FT991A
Interface between wavelog and radio : Wavelog-gate version v.1.0.16
Interface between Wavelog-gate and radio: FLrig 2.0.04
![image](https://github.com/user-attachments/assets/19a8e0e3-1f56-446c-a523-b8e3ba5ec802)

73
VU2TUM

**Comment by int2001** [comment]
pse update to latest WavelogGate - there's a new checkbox/option in it, which prevents changing of the mode:

<img width="142" alt="image" src="https://github.com/user-attachments/assets/80960356-3bf2-49cd-b60b-21ef37b13dc5">

**Comment by spREGR** [comment]
Hi, I updated the wavelog-gate to latest version and the Set MODE via FLrig is checked. Still, the mode changes from CW to LSB or USB

**Comment by int2001** [comment]
na, uncheck it and save it.
Needs to be unchecked!

**Comment by spREGR** [comment]
Thanks, Works now.
