### ISSUE TITLE
UI Bug regarding QSL status

### ISSUE THREAD

**Issue by HB9HIL** [wavelog/wavelog#1269]
### Discussed in https://github.com/wavelog/wavelog/discussions/1267

<div type='discussions-op-text'>

<sup>Originally posted by **gen-intel** November 27, 2024</sup>
Switching between QSL info when you are in Live QSO does not show the individual QSL status. It seems that QSL Card "sticks" to   the selection. i.e when you select LoTW you still see the Card and then on the bottom the LoTW info. This behavior is different in Live QSO compared to looking at a QSO's QSL's when in the "Logbook"

Is this by design?

It's a bit confusing.
 
![Image 11-27-24 at 09 07 (1)](https://github.com/user-attachments/assets/b9a22570-8f8f-4e7e-979e-f4dcadcf1714)
![Image 11-27-24 at 09 07](https://github.com/user-attachments/assets/7501693c-8ac3-44c6-b47e-e21e79aaa47e)
![Image 11-27-24 at 09 08 (1)](https://github.com/user-attachments/assets/2dc74140-488f-40a8-8bd4-e2f66e18e5ec)
![Image 11-27-24 at 09 08 (2)](https://github.com/user-attachments/assets/4d9c1168-fc81-4e9d-9061-0ed039983037)
![Image 11-27-24 at 09 08](https://github.com/user-attachments/assets/c9bdb056-5110-4e15-95f4-b6591345b490)
![Image 11-27-24 at 09 09](https://github.com/user-attachments/assets/1b819c53-b403-4024-b64b-177a8e78cffb)
</div>

**Comment by gen-intel** [comment]
So far so good.
Thank you.
N5HC

**Comment by HB9HIL** [comment]
Bug fixed. Thx for the report @gen-intel
