### ISSUE TITLE
QSL Label printing

### ISSUE THREAD

**Issue by dg9vh** [wavelog/wavelog#128]
**What Feature is Missing?**
When printing labels for modes that are submodes to a mode on the qsl label only the mode would be printed. For example: When using FT4 as submode the mode would be MFSK (what is correct) but the info that it was FT4 is lost.

**Why is This Feature Important?**
It's much more clearer what mode was used exactly for QSLing.

**Is This Feature Personal or Beneficial to Others as Well?**
I think this benefits all users that are logging QSOs via ADIF-import from digimode-programms for example.

**Comment by int2001** [comment]
will check. tnx for input

**Comment by int2001** [comment]
Check #134

**Comment by phl0** [comment]
Checked and tested with 100% result :)

**Comment by dg9vh** [comment]
Will confirm later this day after testing

**Comment by dg9vh** [comment]
Confirmed as working :-) tnx!
