### ISSUE TITLE
weblate not match the code

### ISSUE THREAD

**Issue by hellofinch** [wavelog/wavelog#1335]
Hello,
 I translate the wavelog with weblate. But I get confused. There are some strings I can't find in web page. I click the code link and can't find either. For example this [string](https://translate.wavelog.org/translate/wavelog/main-translation/zh_Hans/?q=state%3A%3Ctranslated&offset=11).
 Maybe some thing has not updated?
: )

**Comment by HB9HIL** [comment]
These are not merged yet and are in weblate due to a mistake by me. Be Patient

**Comment by HB9HIL** [comment]
@hellofinch 

now #1330 is merged and will be available in weblate and code
