### ISSUE TITLE
Contest Logging Live: Different Exch / Serial needed

### ISSUE THREAD

**Issue by DK9JC** [wavelog/wavelog#1348]
Tomorrow is ARRL 10m Contest and was thinking to use Wavelog for logging.

According to the Rules, USA stations (also XE/VE) sending their state as exhange. E.g. 59 CT. Stations not in USA/XE/VE sending a serial number. So would be nice, if it can be set in wavelog accordingly.

Now as is I can chose "Exhange" **for both** or "Serial" **for both** but not Exchange for them and counting n+1 serial for me.

From the ARRL rules:

"Exchange: All stations send a signal report. W/VE stations, including Alaska and Hawaii) send their state
or province. (District of Columbia stations send “DC”.) Mexican stations send their state or province. DX
stations send a serial number. Maritime mobile stations send ITU Region (1-3)"

![2024-12-13 18_30_16-Contest Logging - Wavelog – Mozilla Firefox](https://github.com/user-attachments/assets/4e98f53a-8c7d-4de5-bb13-88df48eff5be)

![2024-12-13 18_30_39-Contest Logging - Wavelog – Mozilla Firefox](https://github.com/user-attachments/assets/cb2c0e6b-7a81-4e85-9806-3f262472fee1)

**Comment by HB9HIL** [comment]
Simply set "Serial + Exchange" and leave fields empty you don't need.

**Comment by HB9HIL** [comment]
PS: In "More Settings" you can adjust the sequence of the fields if needed

**Comment by DK9JC** [comment]
> Simply set "Serial + Exchange" and leave fields empty you don't need.

Thanks Fabian, I will try. 

But it would be better if it would change accordingly. Maybe even with some dependency. If my call does not come from the USA/VE/XE, it could be set automatically maybe that I only give out serial and only receive State/Provice from the other.

(Yes I know Wavelog is not a full contest-logger...)

**Comment by DK9JC** [comment]
Can be closed @HB9HIL 

> Simply set "Serial + Exchange" and leave fields empty you don't need.

Worked.

Thank you.
