### ISSUE TITLE
Logbook front page of wavelog shows distances in km when settings set to miles

### ISSUE THREAD

**Issue by WrathPak** [wavelog/wavelog#1365]
**This is for reporting bugs with the code, if this issue is regarding setting up on your local server please use the discussions area**

**Describe the bug**
I have set up my preferences to show distanes in miles. 

![image](https://github.com/user-attachments/assets/46122a1d-4708-4601-9cc3-f61226e67878)

I see distances in kilometers from the front page of wavelog on the logbook below the map. 

![image](https://github.com/user-attachments/assets/c2c0e280-2c3f-42c4-90f9-3c88f11069f2)

**Version Information**

- Wavelog:          1.8.8 (I did just update to 1.9, issue is still present)

**Steps to Reproduce**
1. Set distance preferences in wavelog to miles, and have distances set as a column in your logbook
2. go to wavelog front page where map and recent qsos are
3. see that the distances are in kilometers on the logbook

**Expected Behavior**

I expect the distances to be in miles if that is what I have selected in preferences.

**Comment by phl0** [comment]
You should update your instance. This has been implemented in version 1.9:
https://github.com/wavelog/wavelog/pull/1331

**Comment by WrathPak** [comment]
@phl0 I did just update. I am on 1.9, issue persists.

**Comment by WrathPak** [comment]
I tried switching distance preferences, then switching back. did not help. still in km. Also tried turning off the distance column on the logbook, then turning it back on. no luck. still shows km. I am definitely on 1.9

**Comment by AndreasK79** [comment]
This was fix right after 1.9 release: https://github.com/wavelog/wavelog/pull/1331
Either switch to dev branch, or wait for the new release.
