### ISSUE TITLE
eQSL Download All Cards Button

### ISSUE THREAD

**Issue by ethancedwards8** [wavelog/wavelog#1397]
**What Feature is Missing?**
On the eQSL card download page (eqsl/download), there should be a button to download all cards instead of having to download each one manually. Maybe a feature could be added where they all download automatically? 

**Why is This Feature Important?**
Simple Quality of life improvement.

**Is This Feature Personal or Beneficial to Others as Well?**
I imagine this would be helpful to many others as well.

**Comment by HB9HIL** [comment]
Hello @ethancedwards8 

A related topic was discussed already here: https://github.com/wavelog/wavelog/issues/1347

Reason that there is no "Download All" Button is that 

a) It's not necessary to download all eqsl cards at once. They get loaded on demand and cached once downloaded. 
b) eQSL does not provide any API which would allow to download all eQSL Cards in one go. Therefore we would need to do it with single calls as it already exists in the eQSL section in Wavelog. But this whole process is not thread-safe and somehow fishy (eQSL is that in general). Therefore we decided to disable the whole "Mass-Download" feature by default in future releases. 

You issue gets marked as Dupe.
