### ISSUE TITLE
Installer Issue

### ISSUE THREAD

**Issue by JnsGSK** [wavelog/wavelog#1408]
I cant connect to the database. I think its because the "-" in the database name.
I cant change the name of the database.

![Wavelog](https://github.com/user-attachments/assets/b0f4a52e-1355-4eb3-8981-3c36db61a77f)

PHP: 8.3.14
MariaDB: v10.11.10

Thanks

**Comment by HB9HIL** [comment]
Hello @JnsGSK 

Thx for this report. I fixed that in `dev` branch. Will be in the next release. Either you use `dev` branch or wait for the next release.

**Comment by HB9HIL** [comment]
For documentation: Fixed with 789b9af52375b4a7cbf50420bfbbe26bf0943c0d

**Comment by JnsGSK** [comment]
Works perfect!
Thank you for the fast Support!
