### ISSUE TITLE
Improve Frequency input

### ISSUE THREAD

**Issue by 205er** [wavelog/wavelog#165]
Hi all,

When displaying a QSO, the frequency will be shown in the following way: 21.300 - Frequency in MHz with dot as decimal separator and three digits as decimal. Unfortunately, you cannot enter a frequency in this format, but it must be entered in Herz. To stick to my example: 21300000 must be entered! If you enter 21.300, the frequency will not be overtaken correctly, but set to the value 21 and displayed as 0.000

Would it be possible to improve this behavior or at least implement a check, so that the input does not get lost?

![Freq](https://github.com/wavelog/wavelog/assets/14996169/75242b87-46ce-45da-be13-53cb0d35a169)
![Freq](https://github.com/wavelog/wavelog/assets/14996169/d62b5053-0f9b-46c0-867e-8d77799fefae)

73

**Comment by HB9HIL** [comment]
Hello @205er 

this is a fair point. We may add a User Option for it so the user can decide which format he wants to use 👍

**Comment by 205er** [comment]
Thanks for your quick and positive response.
At least, it would be greate to have the input checked (ideally directly when leaving this field and not only when the QSO will be saved). This would help to prevent input mistakes.
Making the input user defined would be wonderful! So to say the cherry on the cake 😄

**Comment by dg9vh** [comment]
Good idea... it could be checked against the band-value (if selected) or against some bandplans that in ideal world could be customized by the users with it's boundaries.

**Comment by dg9vh** [comment]
We may not need to have them customizable... was a wrong bias in brain :-)

**Comment by 205er** [comment]
Today i tried out SFLE, which is an fantastic feature! Frequency input in MHz with decimal separator "." is possible (e.g. 21.304) there.
The standard QSO input will not accept this freq. format. :-( Additionally, the band indicator is not logically linked to the frequency, which means you could enter "21,304 MHz" but the band is still set to "80m". When having some pileup, this would easily lead to inconsistency in the heat of the moment.

**Comment by HB9HIL** [comment]
This will take a bit longer since it's quite complex in the qso logging and I need time to dig into this. Please have some patience

**Comment by HB9HIL** [comment]
Solution is merged to dev branch.
