### ISSUE TITLE
Comment field in the Advanced Logbook view

### ISSUE THREAD

**Issue by shadow974** [wavelog/wavelog#194]
Hi,

i would like to have the option to view the comment field of the QSOs in the advanced view. When using FT8 for example, i put the POTA Spot inside the comment at WSJTX. So i can transfer it later into the awards field...

Maybe it would be even better to allow selection of any field to display as a table-row?

vy 73 de Karl, DD7KT

**Comment by AndreasK79** [comment]
Hi,

I can add comment. I have no plans to add every single column.

Andreas.

**Comment by AndreasK79** [comment]
Comment is available in the latest dev branch.

**Comment by phl0** [comment]
works fine :)
