### ISSUE TITLE
Processing new Trainee-Callsigns in Germany with /T as callsign extension

### ISSUE THREAD

**Issue by dg9vh** [wavelog/wavelog#234]
**What Feature is Missing?**
Looking forward to changes in German law we should be able to log and resolve callsigns like DG9VH/T correctly concerning DXCC, CQ-Zone etc.

**Why is This Feature Important?**
Because middle of the year new regulations in Germany will be active we have to procede this correctly then.

**Is This Feature Personal or Beneficial to Others as Well?**
This is beneficial for all users worldwide.

**Comment by int2001** [comment]
Fresh merged to dev. Pse test and comment/close the issue, kim ;)
