### ISSUE TITLE
Bug Repot - Advanced Search result in 500 internal error

### ISSUE THREAD

**Issue by wafer-li** [wavelog/wavelog#271]
**This is for reporting bugs with the code, if this issue is regarding setting up on your local server please use the discussions area**

**Describe the bug**
/search/run_query return 500 internal error, but other search approach results good.

It does not seem to a DB issue, much like the php logic code error.

Because when run the query, it does provide at least one result in the response, but the HTTP Code is 500 and no result output to the page.

**Version Information**
We need some information about your versions. You can get all Information in the Admin > Debug Menu
- OS:       Ubuntu22.4     
- PHP:      8.1       
- MySQL/MariaDB:    5.5.5-10.10.6-MariaDB-1:10.10.6+maria~ubu2204
- Wavelog:      1.4

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'https://<your.domain.com>/search/filter'
2. Click on 'Run query or Search' with any rules that will provide non-empty result

**Expected behaviour**
It should show the result correctly.

**Screenshots**
<img width="1698" alt="image" src="https://github.com/magicbug/Cloudlog/assets/12459199/fc84b0d8-2f32-4970-8497-e44e4ff4c85c">
<img width="670" alt="image" src="https://github.com/magicbug/Cloudlog/assets/12459199/9edccbbe-c036-45fe-abb2-e67c88f26e71">
<img width="972" alt="image" src="https://github.com/wavelog/wavelog/assets/12459199/29df0972-4a81-41c2-b74a-793520c35b68">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome 
 - Version 123.0.6312.107

**Smartphone (please complete the following information):**

**Additional context**
Similar bug with cloudlog before I migrate to wavelog https://github.com/magicbug/Cloudlog/issues/3070

**Comment by wafer-li** [comment]
Sorry, already fixed in `dev` branch.

Looking forward to see the next stable version.

**Comment by AndreasK79** [comment]
Yeah, we found the bug earlier😊 We will soon release a new version.
