### ISSUE TITLE
Bandmap - DXCluster  filtering

### ISSUE THREAD

**Issue by ok1cdj** [wavelog/wavelog#314]
Can you add filter to DXcluster please. New DXCC and not confirmed DXCC.
Thanks.

**Comment by ok1cdj** [comment]
I understand, but when is a lot of spots on the screen you need to scroll down. Filter will be nice, because i am not interested in green ones.

**Comment by HB9HIL** [comment]
@ok1cdj  Your filter is merged and will be released in the next version. If this is okay for your please close this issue :) You can test the filter in the dev branch

**Comment by HB9HIL** [comment]
@ok1cdj We just release Version 1.6. Please test and close this issue if you are happy with it :)

**Comment by ok1cdj** [comment]
Perfect. Thanks.
