### ISSUE TITLE
Unable to complete installation

### ISSUE THREAD

**Issue by N3evin** [wavelog/wavelog#320]
Hi team, I did a clean installation and everything from scratch. However I keep getting 
`Not all fields have been filled in correctly. The host, username, password, and database name are required.`

The database info are working as the "connection test" passed. But when i click install, it keep throwing that error.

OS: Ubuntu 22.04.4 LTS 
Apache: 2.4.52
PHP: PHP 8.1.2-1ubuntu2.15
MySQL/MariaDB: 10.6.16
Wavelog: latest master branch

Edit:
found this in apache2 error log `PHP Warning:  Undefined array key "database_check" in /var/www/html/install/index.php on line 94, referer: http://domain.com/install/`

**Comment by N3evin** [comment]
> hello, the email field is necessary too. i started a fix few days ago ... i have to finish it ;)

thank you, but I did add my email.

**Comment by N3evin** [comment]
I think i might had it resolved, but callsign or locator seems to be required. Or else it throw the error.

**Comment by HB9HIL** [comment]
@N3evin so it's resolved?

**Comment by N3evin** [comment]
> @N3evin so it's resolved?

Yes it had been resolved, solution should be that it required a callsign
