### ISSUE TITLE
Release archive 1.6 does not contain files of recent master branch.

### ISSUE THREAD

**Issue by 205er** [wavelog/wavelog#399]
I just noticed, that the downloadable archive at https://github.com/wavelog/wavelog/releases/tag/1.6 does not contain the files of Version 1.6, but from release 1.5.1

![ZIP](https://github.com/wavelog/wavelog/assets/14996169/4b36683f-0a05-4720-a29a-3712890fbfd4)

**Comment by phl0** [comment]
This was corrected 30 min ago. Pls try again.

**Comment by 205er** [comment]
Thanks for your quick reply and for providing a solution!
It took me a while to realize that I did not make a mistake. Very confusing ;-) In the meantime I downloaded the content of the master branch that helped me updating my Wavelog instance.

**Comment by 205er** [comment]
Thanks!
