### ISSUE TITLE
Enabled QSL-Methods not shown correctly in Logbook Overview

### ISSUE THREAD

**Issue by zone11** [wavelog/wavelog#412]
**Describe the bug**
With having one or multiple QSL-Methods enabled in the account, disabling QSL results in hiding the LoTW column instead of QSL column in Logbook overview.
In this example, only enabling LoTW is described.

**Version Information**
- OS:               FreeBSD
- PHP:              8.1
- MySQL/MariaDB:    10.6.16
- Wavelog:          1.6 

**Steps to Reproduce**
1. Go to 'Account'
2. Click on 'Default Values'
3. Enable "LoTW" only
4. Got to Logbook -> Overview
5. See the QSL column instead of LoTW

**Expected Behavior**
Only show the enabled QSL-Methodes columns

**Screenshots**
Settings
<img width="638" alt="Bildschirmfoto 2024-05-26 um 12 36 04" src="https://github.com/wavelog/wavelog/assets/1774084/bd51c5d1-d597-4f2f-adda-a0a36882c53d">

Logbook Overview
<img width="1339" alt="Bildschirmfoto 2024-05-26 um 12 36 17" src="https://github.com/wavelog/wavelog/assets/1774084/82d200aa-e126-4c96-9361-90fae97397d6">

**Desktop Information:**
- OS:               MacOS 14.5
- Browser:         Chrome / Safari
- Version:          17.5 / 125.0.6422.76

**Comment by int2001** [comment]
Can confirm the bug.
Working on it. Tnx for reporting

**Comment by zone11** [comment]
Tnx for fixing!
