### ISSUE TITLE
Add the ability to set a default radio used for live QSO

### ISSUE THREAD

**Issue by zone11** [wavelog/wavelog#418]
**What Feature is Missing?**
I would recommend adding the ability to define a default radio (from the hardware interface list) to be used on the "Live QSO" page. Alternative would be storing the last selected radio within the user.

**Why is This Feature Important?**
Using hardware interfaces is an awesome feature, but every time you navigate around Wavelog, coming back to add a live QSO, you need to set the radio first. The feature would save time getting ready, especially in hectic moments.

**Is This Feature Personal or Beneficial to Others as Well?**
It's definitely a benefit for every user of a hardware interfaces in Wavelog

**Comment by wafer-li** [comment]
And maybe adding the "default ANTENNA" as well?

**Comment by HB9HIL** [comment]
@zone11 

Started to work on this. PR #700 is still drafted but feel free to test.

**Comment by zone11** [comment]
@HB9HIL I've done a quick functional test, works fine and the implementation is very user friendly. Tnx!

**Comment by HB9HIL** [comment]
The "default radio" handler is now available in `dev` branch and will be published in the next release.

**Comment by zone11** [comment]
Thank you for the implementation!
