### ISSUE TITLE
Did not see the added QSO

### ISSUE THREAD

**Issue by ds2k5** [wavelog/wavelog#425]
Hello,
had Version 1.5.x and did Update to 1.6

Now tryed to add my 1st QSO ( QSO -> Manuel  .../wavelog/index.php/qso?manual=1 )
but is no show add the main page or Logbook -> Overview
In Logbook -> expanded I can find it.

![grafik](https://github.com/wavelog/wavelog/assets/11292286/b84acb32-1d00-4db3-8849-0f9113b4159b)

![grafik](https://github.com/wavelog/wavelog/assets/11292286/c60c14e7-0412-4179-a3e7-6482aaf50653)

![grafik](https://github.com/wavelog/wavelog/assets/11292286/8bad5438-55f4-4113-a063-1599df21592c)

What did I wrong ?

**Comment by HB9HIL** [comment]
Please check if the active station location is linked with the active station logbook. (see at Stationsetup)

**Comment by ds2k5** [comment]
thank you so much that was the solution!
