### ISSUE TITLE
printmap only white background

### ISSUE THREAD

**Issue by ds2k5** [wavelog/wavelog#432]
Hello,
using Version 1.6

When using "printmap" got only a white background.

![image](https://github.com/wavelog/wavelog/assets/11292286/4e654081-3fac-426c-80ee-b9fb5dcf37ad)

![myMap(1)](https://github.com/wavelog/wavelog/assets/11292286/e2fefe73-c079-4056-a4a5-54248096349b)

What did I wrong ?

**Comment by HB9HIL** [comment]
Can you please try that in "Logbook Advanced" aswell?

<img width="465" alt="image" src="https://github.com/wavelog/wavelog/assets/80885850/9358814d-9ca7-4288-aeae-69f28c0f0a4f">

Click "Map" and print the map from there.

**Comment by ds2k5** [comment]
@HB9HIL   the same issue

![Wavelog](https://github.com/wavelog/wavelog/assets/11292286/26eee5bd-0886-4cd7-bee1-160c9f1bc6db)

**Comment by HB9HIL** [comment]
Did you change the maptile server manually?

**Comment by ds2k5** [comment]
>Did you change the maptile server manually?

no did not know how :-)

**Comment by ds2k5** [comment]
Thank you.... disabled all in Firefox - no change

Tryed: chromium there I works

**Comment by HB9HIL** [comment]
> Thank you.... disabled all in Firefox - no change
> 
> Tryed: chromium there I works

Firefox is sometimes kinda tricky
