### ISSUE TITLE
no distance analyse will be show

### ISSUE THREAD

**Issue by ds2k5** [wavelog/wavelog#433]
Hi,
using Version 1.6
have to QSOs added but no data in the distance analayse.
What did I wrong ?

![image](https://github.com/wavelog/wavelog/assets/11292286/cd7b493e-a582-477f-8f76-df2e52dbeecc)

Can see the 2 QSOs in ../wavelog/index.php/statistics

![image](https://github.com/wavelog/wavelog/assets/11292286/a501049b-8976-4bcf-be23-1cfe0904e7e2)

**Comment by HB9HIL** [comment]
Hello @ds2k5 

You can check two things. 

- First make sure that the QSO does hava a valid grid locator and your station location does have a valid gridsquare aswell
- Go to "Admin -> Update Country Files -> Second Tab "Distance Data""

Here you can Wavelog let recalculate missing distance data. 

Try that.

**Comment by ds2k5** [comment]
Thanks a lot ! sorry my fault! did not set the gridsquare!
