### ISSUE TITLE
Gridsquare Map mixing SAT and others QSOs

### ISSUE THREAD

**Issue by ok1cdj** [wavelog/wavelog#469]
How to filter out SAT QSOs on Gridsquare Map and show only terrestrial ? I think this worked before update.
![image](https://github.com/wavelog/wavelog/assets/672504/bda909c9-01df-4b7a-9804-b1f61fe293e5)

**Comment by int2001** [comment]
@ok1cdj since there's a new filter with "Propagation == empty" now, can we close this topic?

**Comment by ok1cdj** [comment]
Hello, this is not working for me. Because i  am using TROPO or ES or MS in Propagation field.
I just need filter out all QSOs with propagation SAT.

Thank you very much. 73 Ondra

**Comment by int2001** [comment]
Roger.
Added a new Select with #496 - could you pse test?

<img width="516" alt="image" src="https://github.com/wavelog/wavelog/assets/1410708/277d7fcc-cc4c-4ba1-bb67-39caba70e1cd">

**Comment by ok1cdj** [comment]
Great. Thanks.
