### ISSUE TITLE
V 1.6.1 - eQSL Download hängt

### ISSUE THREAD

**Issue by ds2k5** [wavelog/wavelog#475]
Hallo,
habe die Version 1.6.1 im Einsatz.
Hab da ein Problem das ein eSQL von einem QSL hängt.
Ursache ist vermutlich das ich auf eQSL die QSL Karte nicht mehr sehe.
Der Absender diese vermutich gelöscht hat !?
Wavelog diese aber gesehen hat und diese runterladen will.

Third party services -> eSQl ... -> Download eQSL Cards

![grafik](https://github.com/wavelog/wavelog/assets/11292286/8e21ca45-d5e3-4688-ae08-500568f0a897)

![grafik](https://github.com/wavelog/wavelog/assets/11292286/648159d9-a025-47cf-8ad8-7eae2991a124)

![grafik](https://github.com/wavelog/wavelog/assets/11292286/634fdc45-0ee2-465d-aafe-f585838c220f)

Neuere eSQL Karten werden so auch nicht geladen.

Wie kann ich das beheben ?

**Comment by int2001** [comment]
Du kannst sie manuell (Edit QSO) versuchen auf "No" zu setzen.
Dann sollte(!) sie auch nicht mehr versucht werden runterzuladen.

<img width="875" alt="image" src="https://github.com/wavelog/wavelog/assets/1410708/c139f0ab-bee6-4dd9-bf45-5d2866f38f2a">

**Comment by ds2k5** [comment]
@int2001

vielen Dank.... das ging soweit das ich
keine Fehler mehr hab

Es kamen aber keine eQSL Karten mehr rein..
aber gut versuch ich von hand runterladen und dann hochladen

**Comment by ds2k5** [comment]
@int2001 

Nun habe ich ein eSQL Karte im Eingang bei eqsl.cc

![grafik](https://github.com/wavelog/wavelog/assets/11292286/6fa6f6ca-a871-4497-b1d3-c2249089d49f)


aber Wavelog behauptet immer noch es gäbe keine eSQL Karten zum download

![grafik](https://github.com/wavelog/wavelog/assets/11292286/c9a79659-cdf2-4eb4-bc21-22e09a5f268a)

**Comment by int2001** [comment]
Auch nicht wenn du erst auf "Download QSOs" drückst?!

**Comment by ds2k5** [comment]
@int2001 
leider nein

**Comment by int2001** [comment]
Und das entsprechende QSO existiert auch bei Dir im Wavelog und ist entsprechend zu eQSL hochgeladen worden?

Mit gleichen Angaben zu Zeit, Band und Mode?

Ansonsten schick mir bitte mal eine Mail, dann schau ich mir das im 1:1 mit Dir mal an, wenn Du magst und wir einen Termin finden.

Mailadresse unter qrz.com ersichtlich.

DJ7NT

**Comment by ds2k5** [comment]
ja

![grafik](https://github.com/wavelog/wavelog/assets/11292286/a355700f-0bc1-4a5b-9d25-2f6d0d8915ac)

**Comment by ds2k5** [comment]
@int2001 vielen Dank für die Lösing:

![grafik](https://github.com/wavelog/wavelog/assets/11292286/006bb0e5-fdab-424a-932c-26e003d18e00)

Hier auf Import klcken

dann sind die QSL Karte zum DL da...

![grafik](https://github.com/wavelog/wavelog/assets/11292286/b39490c1-81dd-4c66-8c8c-7aaaf312984f)
