### ISSUE TITLE
WavelogBashCat Broken Link

### ISSUE THREAD

**Issue by n1zzo** [wavelog/wavelog#535]
The link to WavelogBashCat in the Wiki is broken, and the software is nowhere to be found in the web.
Is the tool deprecated? Can you point to any alternative to interface wavelog with rigctld?

Thanks,

Niccolò, IU2KIN

**Comment by HB9HIL** [comment]
@n1zzo 

You may looking for https://github.com/g0wfv/CloudlogBashCat

There is no "WavelogBashCat"

BUT

We have WavelogGate which handles the Connection between FLrig and Wavelog

See here: https://github.com/wavelog/WaveLogGate

**Comment by n1zzo** [comment]
Great,thank you so much for the quick reply, I’ll try to setup one of the two.Feel free to close the issue, thanks!NiccolòIl giorno 2 lug 2024, alle ore 22:22, HB9HIL ***@***.***> ha scritto:﻿
@n1zzo
You may looking for https://github.com/g0wfv/CloudlogBashCat
There is no "WavelogBashCat"
BUT
We have WavelogGate which handles the Connection between FLrig and Wavelog
See here: https://github.com/wavelog/WaveLogGate

**Comment by HB9HIL** [comment]
Note: Adjusted Wiki Entry for "Radio-Interface" and fixed broken links.
