### ISSUE TITLE
LoTW upload fails for QSO with PROP_MODE unsupported by LoTW

### ISSUE THREAD

**Issue by dl3jop** [wavelog/wavelog#562]
If you selected a PROP_MODE which is not supported by LoTW, the processing of the file fails on the LoTW server side.
List: [https://groups.arrl.org/g/ARRL-LoTW/topic/modes_that_can_be_submitted/26868793](url)

Steps to reproduce:
Create a QSO with propagation set to RPT. The upload works, but LoTW will not process it.
The log on the LoTW Activity page is as follows:
`
LOTW_QSO: Processing terminated with an unexpected failure. System administrator has been notified.`

It looks like all QSO in that upload are not processed, even if just one is set to one of the non supported propagation modes

**Comment by dl3jop** [comment]
I think @phl0 is already looking for a fix :)

**Comment by phl0** [comment]
Fix proposed in https://github.com/wavelog/wavelog/pull/563.

**Comment by Loki1737** [comment]
Thank you @phl0 , that you are fixing this issue. I did run into the same issue, and did not realise it, until shortly.
