### ISSUE TITLE
Docker new Language not working

### ISSUE THREAD

**Issue by zaubererty** [wavelog/wavelog#569]
**Describe the bug**
Upgraded from a working 1.6 docker setup to 1.7 and got following error

![image](https://github.com/user-attachments/assets/0e9c7bb6-db3a-4b25-b5b5-76a604962871)

**Version Information**
Docker container 1.7

**Comment by HB9HIL** [comment]
Can you please try to restart the container again and delete browser cache?

meanwhile I will test an upgrade from 1.6 to 1.7

**Comment by zaubererty** [comment]
Did recreate the whole stack, did not change anything

**Comment by HB9HIL** [comment]
Looks your `docker-compose.yml` **exactly** like this?  :
https://github.com/wavelog/wavelog/wiki/Installation-via-Docker#docker-composeyaml

Did you upgrade like this:

Stop the container:
```bash
docker compose down
```

Repull
```bash
docker compose pull
```

Restart the container
```bash
docker compose up -d
```

**Comment by HB9HIL** [comment]
I just tested an upgrade from 1.6 to 1.7
works as expected here

**Comment by zaubererty** [comment]
My docker-compose.yml looks like this

`version: '3'

services:
  web:
    image: ghcr.io/wavelog/wavelog:latest
    restart: unless-stopped
    networks:
      - external_network
      - internal_network
    depends_on:
      - mariadb
    volumes:
      - ${PATH_TO_APPDATA}/wavelog/storage/config:/var/www/html/application/config/docker
      - ${PATH_TO_APPDATA}/wavelog/storage/logs:/var/www/html/application/logs
      - ${PATH_TO_APPDATA}/wavelog/storage/backup:/var/www/html/backup
      - ${PATH_TO_APPDATA}/wavelog/storage/uploads:/var/www/html/uploads
      - ${PATH_TO_APPDATA}/wavelog/storage/userdata:/var/www/html/userdata
    ports:
      - 8082:80
  mariadb:
    restart: unless-stopped
    image: mariadb:11.3
    networks:
      - internal_network
    volumes:
      - ${PATH_TO_APPDATA}/wavelog/db:/var/lib/mysql
  adminer_container:
    image: adminer:latest
    ports:
      - 8089:8080
    networks:
      - internal_network
      - external_network

networks:
  external_network:
  internal_network:
    internal: true
`
What files need to be in the docker specific config folder?

**Comment by HB9HIL** [comment]
@zaubererty This is far away from the default setup. I'm no docker expert. Maybe @int2001 can help here.

But I'm 99% sure that this is no Wavelog Code Issue. 

> What files need to be in the docker specific config folder?

only `config.php` and `database.php`

ALL other files are laying in `application/config`

One way to solve that is delete all config files in `application/config/docker` except the two mentioned

**Comment by zaubererty** [comment]
Got it working, thank you for the tips
