### ISSUE TITLE
DX calendar 

### ISSUE THREAD

**Issue by jwussler** [wavelog/wavelog#619]
PHP Version | 8.3.9 OK
MySQL Version | 11.3.2-MariaDB-1:11.3.2+maria~ubu2204
Codeigniter Version | 3.2.0-dev

the DX colander under the tools menu is tossing a 500 error

i can also log into the demo site at wavelog.org and produce  the same error

**Comment by HB9HIL** [comment]
You are right. here seems to be an issue

**Comment by HB9HIL** [comment]
Dupe #620

**Comment by int2001** [comment]
Seems like the DXPedition to Mariana Island causes this trouble.
The DXPedition is across new years eve. So it starts in 2024 and ends in 2025.
Since the Date isn't really well formatted it can currently not be parsed well by Wavelog.

We're trying to fix that. CC: @AndreasK79
