### ISSUE TITLE
Changeing QSL-State in advanced log results in errorneous displaying

### ISSUE THREAD

**Issue by dg9vh** [wavelog/wavelog#625]
**Describe the bug**
Icons in "QSL" are changed in weird way.

**Version Information**
We need some information about your versions. You can get all Information in the Admin > Debug Menu

- Wavelog:         Version 1.7

**Steps to Reproduce**
1. Go to advanced log and search for "QSL send" = "no" and "QSL received" = "yes" to find incoming but not confirmed QSLs:

![image](https://github.com/user-attachments/assets/5fd5c065-762a-4706-a861-3a7a1c18f3f9)

Resulting Display is following in QSL-state:
![image](https://github.com/user-attachments/assets/26af9f33-01d5-45f5-8fc6-8d29eedb4dea)

2. mark specific QSO to be printed by selecting it and click on "requested (buro)" to queue the QSL-Card, this results in following state-display:
![image](https://github.com/user-attachments/assets/f318f870-ad55-416a-bbdf-7fd390e61019)
3. you can see the weird changeing of the status-icons after the action.
4. When searching explizit for the changed QSO by using quickfilter and callsign, you find the correct icon-placing after refreshing by search:
![image](https://github.com/user-attachments/assets/614e5bf1-e7fd-48b8-8d2b-bd3125bb56f6)

**Expected Behavior**
The correct icons should be changed in color.

**Desktop Information:**
- OS:               Windows 10
- Browser:         Chrome
- Version:         126.0.6478.183

**Comment by AndreasK79** [comment]
@dg9vh nice find. The update function had swapped column for Club Log and QSL. It's fixed in dev now.
