### ISSUE TITLE
during installation lots of DXCC countries are marked as deleted

### ISSUE THREAD

**Issue by nobswolf** [wavelog/wavelog#630]
**This is for reporting bugs with the code, if this issue is regarding setting up on your local server please use the discussions area**

**Describe the bug**
Germany is not available in the DXCC list during installation

**Version Information**
- Wavelog:          1.7 (git)

**Steps to Reproduce**
1. use installer
2. try to select Germany DL
3. is marked as deleted
4. is not accepted as selection

**Expected Behavior**
DL should be available (later in the normal running web-site it is)

**Comment by phl0** [comment]
This is on purpose because that is the wrong DXCC. The correct one is Federal Republic of Germany (DXCC No 230)

**Comment by nobswolf** [comment]
Ah, true... 

Then maybe it is a good idea to make this a searchable list, so you can type "Germ..." and find all entries with the search string in it and not only the ones that start with it.

**Comment by nobswolf** [comment]
made this a feature request:

https://github.com/wavelog/wavelog/issues/633

**Comment by nobswolf** [comment]
works as intended
