### ISSUE TITLE
Update RST(S) RST(R) when using favorites

### ISSUE THREAD

**Issue by Nailcoding** [wavelog/wavelog#642]
When setting band/mode in Live-QSO via favorites, the RST(S) and RST(R) dont't get updated. If CW was set before and switched to SSV, the default in the fields stays at 599 599. When switching to SSB via dropdown, it turns to 59 59. Would be nice if it also gets update when using favorites

**Comment by HB9HIL** [comment]
Hello @Nailcoding 

this one is fixed in dev branch. Please test and close this issue if it fixes your issue as expected :)
