### ISSUE TITLE
Names vs. Keys on contest select lists

### ISSUE THREAD

**Issue by dg9vh** [wavelog/wavelog#656]
**Describe the bug**
On different places different representations for the contests are in the select-lists:
On the contest log window you'll find the names as you'll find them on the contest-calendar (for most of them, we have to put some hands on this maybe to be synchronized with this):
![image](https://github.com/user-attachments/assets/e2950ff8-7154-4525-9c74-dfcf5995a706)

If you switch over to Cabrillo export, you'll find the contests with their keys form the contests-table:
![image](https://github.com/user-attachments/assets/0627e2ca-547a-43b5-97e2-65eafb030f26)

Now, if you go to the edit-window for QSO details, you'll find again the names:
![image](https://github.com/user-attachments/assets/bad3f3e4-397e-4871-98c0-e8f8395dd943)

This is also on batch edit in advanced log:
![image](https://github.com/user-attachments/assets/a496eb66-1d91-4869-a803-881ce9b4ceef)

But here is the problem (did not test it on the edit above), that if you would change a contest to another name, the contest entry is completely deleted.

Running on Wavelog 1.7 Release version.

**Comment by AndreasK79** [comment]
#663 added. Now uses name in Cabrillo export if available, if not id as before.

What do you mean when you say that the contest entry is completely deleted?

**Comment by AndreasK79** [comment]
@dg9vh fix is in dev, so this should be ok now.
