### ISSUE TITLE
Québec station location province breaks LoTW uploads

### ISSUE THREAD

**Issue by anthonydiiorio** [wavelog/wavelog#689]
I cannot upload to LoTW with my Station Location Province set to Québec.

I'm not sure if it's because of the accented é breaking something somewhere.

If I set my Province to Ontario for example I can upload my QSOs. I can also upload my QSOs if I set my station province to blank.

![image](https://github.com/user-attachments/assets/e8aef27f-8ff0-404f-8d3a-3596cdaeeb7b)

**Version Information**
- Server Software	Apache/2.4.61 (Debian)
- PHP Version	8.3.9
- MySQL Version	11.3.2-MariaDB-1:11.3.2+maria~ubu2204
- Wavelog 1.8 (Docker)

**Steps to Reproduce**
1. Station Setup
2. Edit Station Location
3. Set DXCC to Canada and Province to Québec
4. Log a QSO and upload to LoTW

**Expected Behavior**
Upload QSOs to LoTW

**Actual Behavior**
LoTW Error
`2024-08-03 07:07:01 LOTW_QSO: Error in record 3: Unable to verify tCONTACT signature: QSOVerify failed - Verification failed`

TQSL
![image](https://github.com/user-attachments/assets/3e434048-439a-4ae9-b07b-89e2fae11f50)

QSO Uploaded from TQSL
![image](https://github.com/user-attachments/assets/1df5b065-6b94-4ddb-bdb2-fd84191b403b)

QSO Uploaded with Blank province in Wavelog
![image](https://github.com/user-attachments/assets/1593ab28-5f75-47de-b1d6-f316919c4067)

QSO Uploaded with Québec in Wavelog
![image](https://github.com/user-attachments/assets/e149b85c-3091-4819-b55a-6093b19c8336)

**Comment by HB9HIL** [comment]
@phl0 Could this be related to this one?

https://github.com/wavelog/wavelog/commit/4a847de5a62afecd661611b1b8f566f82a720baf

**Comment by phl0** [comment]
I will have a look. Can you please provide a screenshot of the station location config in Wavelog?

**Comment by anthonydiiorio** [comment]
@HB9HIL 
> Could this be related to this one?
> 
> [4a847de](https://github.com/wavelog/wavelog/commit/4a847de5a62afecd661611b1b8f566f82a720baf)

I tried commenting this out and LoTW doesn't like QC
`LOTW_QSO: Error in record 2: CA_PROVINCE: Invalid value in field (QC)`

I checked the TQSL source and Quebec is mapped to PQ as well so this should be ok. https://sourceforge.net/p/trustedqsl/tqsl/ci/master/tree/src/config.xml#l724

@phl0 
> I will have a look. Can you please provide a screenshot of the station location config in Wavelog?

![image](https://github.com/user-attachments/assets/f8f7f2b4-c3ac-4f25-82ff-c8a558516b2b)

**Comment by anthonydiiorio** [comment]
There's definitely something up with `lotw_ca_province_map`, I tried Newfoundland and Labrador which is also covered by this function and it also breaks the upload. Then switched to a different province and it uploads normally.

**Comment by HB9HIL** [comment]
Solved in the current release 1.8.1

Please test and close this issue if everything works as expected :)

**Comment by anthonydiiorio** [comment]
Running smooth! Thanks 😄
