### ISSUE TITLE
eQSL Cron Job not working if password contains <

### ISSUE THREAD

**Issue by boomesito** [wavelog/wavelog#695]
**Describe the bug**
If eQSL password contains a `<` cron job for up- and downloading from eQSL does throw the error _eQSL: Your eQSL username and/or password is incorrect._

**Version Information**
- official Wavelog Docker image
- Wavelog: 1.8 

**Steps to Reproduce**
1. Create an eQSL account with password containing `<`
2. setup cron manager for up- and download from/to eQSL
3. enable error/debug logging in config.php
4. See error invalid user or password in logfile

**Additional Context**
- if you run the upload manually from third party services menu it works
- for debugging I logged the password and figured out, that `<` was converted to `&lt;`

**Comment by HB9HIL** [comment]
@boomesito 

Do you know how to test a PR branch? :)

**Comment by HB9HIL** [comment]
@boomesito 

I tested the password `test<test` in current `dev` branch at it sucessfully uploads the QSO to eQSL.cc. 

There is may another issues? 

Please change your password on eQSL and in Wavelog and provide me the password here.

**Comment by boomesito** [comment]
@HB9HIL the password not working was `\Y+ZbZDF<*kJ\%`
By changing `<` to `$` it worked in currend 1.8 docker image.

**Comment by HB9HIL** [comment]
Hello @boomesito 

Thx for providing the password (I hope you changed it)

I tested `\Y+ZbZDF<*kJ\%` with my own eQSL Account and the QSO's just uploaded fine. On a standard installation, also on the current docker package. 

I assume that you may had a typo in your password, which is now fixed. But I can't reproduce the issue with `\Y+ZbZDF<*kJ\%`

In my eyes this one is fixed...

**Comment by boomesito** [comment]
Hello @HB9HIL 

of course I changed my password and the new one is working. I dont't believe it was a typo as it worked when in started sync from the menu. It only didn't work when update was done with the cron job.

**Comment by HB9HIL** [comment]
Let me check again

**Comment by HB9HIL** [comment]
Finally found the issue. Thanks for the hint again that it did no work via Cron but worked via GUI

Fix in #696

**Comment by HB9HIL** [comment]
@boomesito 

issue is fixed. Will be in the next master release.

If you run your docker installation on the dev branch you can repull the image in a few minutes to test the change.

**Comment by HB9HIL** [comment]
Solved in the current release 1.8.1

Please test and close this issue if everything works as expected :)

**Comment by boomesito** [comment]
Works with current release
