### ISSUE TITLE
"Gridsquare Activators" search issue with CALL/VO1 - multiple grid locators in "gridsquare"

### ISSUE THREAD

**Issue by DK9JC** [wavelog/wavelog#726]
When I looked in "Gridsquare Activators" I could not found those entries from a rover from CALL/VO1.

I tracked down the issue to all those QSO were made from a gridline. Both grids logged into "Gridsquare". With most of wavelog now supporting it, it causes a "ignore" in the search results.

- PHP:              8.1.29
- MySQL/MariaDB:  10.5.25-MariaDB
- Wavelog:          1,8.2 (was before also 1.7.2 )

![2024-08-10 17_21_35-Window](https://github.com/user-attachments/assets/8a136f27-0a42-45c5-bd26-3072f6aa61f0)
![2024-08-10 17_21_17-Advanced logbook - Wavelog – Mozilla Firefox](https://github.com/user-attachments/assets/59571661-a9f8-40b1-9aa4-b62d071c1e9d)

**Comment by AndreasK79** [comment]
@DK9JC I found some problems in the code, and can reproduce this problem. Thanks for reporting! Not sure when a fix will be in place, but it's being looked into.

**Comment by DK9JC** [comment]
thanks for looking. 
good it can be reproduced.

**Comment by AndreasK79** [comment]
@DK9JC if you pull latest dev, the issue should now be fixed!

**Comment by DK9JC** [comment]
> @DK9JC if you pull latest dev, the issue should now be fixed!

![2024-08-19 15_52_43-Gridsquare Activators - Wavelog – Mozilla Firefox](https://github.com/user-attachments/assets/0d690e59-2050-4edf-8dee-8d51bd9ea38d)

fixed, thank you!!
