### ISSUE TITLE
Map export is not working correctly

### ISSUE THREAD

**Issue by derFogel** [wavelog/wavelog#727]
If you press this button in the map of the advanced logbook:
![image](https://github.com/user-attachments/assets/18505322-d236-4ce0-b81f-0b145cc6b057)

Then the resulting image looks like this:
![image](https://github.com/user-attachments/assets/640be767-9e50-43f0-b887-ad9c8ba470c0)

But I would expect something like this:
![image](https://github.com/user-attachments/assets/aaf9edea-35f2-4b3c-97ae-1c85dbc6f8e9)

Version: 1.8

**Comment by DK9JC** [comment]
I can confirm w 1.8.2

to be more specific:

the downloaded file Wavelog,png has the problem. 

the view in wavelog itself looks correct.

**Comment by AndreasK79** [comment]
I can't reproduce this. Which browser are you guys using?

**Comment by derFogel** [comment]
I am using firefox 127.0.2

**Comment by AndreasK79** [comment]
See here: https://github.com/wavelog/wavelog/issues/432 Seems Firefox might have some trouble.

**Comment by derFogel** [comment]
ok, so close as duplicate?

**Comment by derFogel** [comment]
Turns out there are bug reports on leaflet-easyprint going back to 2017 with the same problem.

**Comment by DK9JC** [comment]
> I can't reproduce this. Which browser are you guys using?

FF 129.0

**Comment by AndreasK79** [comment]
> Turns out there are bug reports on leaflet-easyprint going back to 2017 with the same problem.

So they are aware, but no fix exists I guess. I don't remember if I checked last time it was reported, I just remembered that someone had similar problems before.
