### ISSUE TITLE
Adding new LoTW callsign certificate fails

### ISSUE THREAD

**Issue by dl3jop** [wavelog/wavelog#746]
Adding a new *.p12 callsign certificate fails with following error in the log:
`Severity: Warning --> Undefined array key "cert" /var/www/html/application/controllers/Lotw.php 408
error:0308010C:digital envelope routines::unsupported`

Steps to reproduce:
Upload new *.p12 certificate in LoTW tab.

Used version: 
master, latest commit: 646ccf2783042ba6390cea1ecc5ab4d3996b7b3c

**Comment by phl0** [comment]
Which version of tqsl did you take to export the certificate?

**Comment by phl0** [comment]
> Arrgh, it wasn't up to date on my travel laptop.... Thanks for the hint, now works as expected.

I was about to tell that :-)
