### ISSUE TITLE
Weblate Translation - Automatic suggestions error

### ISSUE THREAD

**Issue by kikosgc** [wavelog/wavelog#764]
Getting an error during translation for wavelog via weblate -
> The request for machine translation using OpenAI has failed: InternalServerError: Error code: 502 - {'error': {'code': 502, 'message': 'Bad gateway.', 'param': None, 'type': 'cf_bad_gateway'}}

73 de CT7AJM / F4VSE 

PS: This error seems to be random and doesn't happen all the time.

**Comment by HB9HIL** [comment]
Which browser do you use?
