### ISSUE TITLE
Contest Calendar 500 error

### ISSUE THREAD

**Issue by jwussler** [wavelog/wavelog#773]
I am on 1.8.2 dev branch and the contest calendar page tossing a 500 error

**Comment by AndreasK79** [comment]
@jwussler thanks for reporting it. I've pushed a small fix (to dev) so that the page will load.
The date/time parser needs to be updated, but at least the page will load. For now it displays blank where it can't parse correctly.

**Comment by HB9HIL** [comment]
I think the main issue (error 500) is fixed. So probably we can close this one
