### ISSUE TITLE
Report basic errors in Simple Fast Log Entry (SFLE) right away

### ISSUE THREAD

**Issue by filipmelik** [wavelog/wavelog#803]
**What Feature is Missing?**
When you use the FLE functionality for logging QSO's (as I do when I am on portable) and you do not specify the basic information, like band or mode, the error is reported to you when "Save in Wavelog" button is pressed. It would be cool to know this information up-front, even before you start the logging, just to improve the UX a little. Especially, when the source code is ready for it (but there is a little bug in it, I plan to inform the upstream source author OK2CQR about this and fix it on his side too).

**Steps to Reproduce**
1. Go to 'QSO > Simple Fast Log Entry'
2. Paste following to the textarea: 
ok12asd
adas3sda
3. See that no error is displayed, even though the basic info about the band/mode/time is missing

**Expected Behavior**
Errors should be presented to user right away to know he should add the basic data

**Why is This Feature Important?**
I believe this would improve the FLE entry's UX

**Is This Feature Personal or Beneficial to Others as Well?**
I hope so :)

**Screenshot of the current state**
<img width="765" alt="Screenshot 2024-08-25 at 8 40 19" src="https://github.com/user-attachments/assets/f88954d2-84a7-455b-89ef-722722d91ae9">

**Screenshot of the proposed state**
<img width="865" alt="Screenshot 2024-08-25 at 8 40 33" src="https://github.com/user-attachments/assets/07eb503c-f90c-4d5e-ae7b-3480ce47984a">

**Additional Context**
I have already fixed it on my side. If you think this is beneficial to others I will submit a PR.

**Comment by HB9HIL** [comment]
Go ahead 😁

**Comment by filipmelik** [comment]
Aye aye captain 😁 https://github.com/wavelog/wavelog/pull/804
