### ISSUE TITLE
Cannot enter or edit ITU-ZONE in qso

### ISSUE THREAD

**Issue by Beiri22** [wavelog/wavelog#810]
**Describe the bug**
In my QSO-List only one has the ITU-Zone set. However, I do not know how, because there is no ITU-Zone input field in Live/Post-QSO, neither in the "edit qso" dialoge. Do I miss something?

Wavelog Version	1.8.2 via Docker

**Comment by Beiri22** [comment]
Thank you. Just as I'm curious: Could the ITU Zone be prefilled based on location / grid square ?

**Comment by HB9HIL** [comment]
> Thank you. Just as I'm curious: Could the ITU Zone be prefilled based on location / grid square ?

Currently we do not have a good datasource for that. But we have that in mind

**Comment by Beiri22** [comment]
When using qrz.com data, you could import it if available. How do they do it ... https://zone-check.eu/? Could we just query it?

**Comment by HB9HIL** [comment]
Should be fixed :)

**Comment by Beiri22** [comment]
Thank you!
73 de DO4MIT
