### ISSUE TITLE
Bug Report: Mastodon URL Under Profile Section Doesn't Save

### ISSUE THREAD

**Issue by spREGR** [wavelog/wavelog#837]
When attempting to save a Mastodon URL under the profile section in Wavelog, the application results in a blank page if the full URL is entered. However, the profile section does accept a simplified version of the URL. This behavior is problematic because, in order to Toot from Wavelog, Mastodon expects the full URL, including the "DECK" path, e.g., https://mastodon.radio/deck/@vu2tum.

Steps to Reproduce:

    Navigate to the profile section in Wavelog.
    Enter the full Mastodon URL, e.g., https://mastodon.radio/deck/@vu2tum.
    Attempt to save the URL.
    Observe that the application results in a blank page.

Expected Behavior:

The full Mastodon URL, including paths like "DECK," should be accepted and saved without issue.

Actual Behavior:

The application results in a blank page when a full Mastodon URL is entered, and the URL is not saved.

Workaround:

Currently, only the simplified version of the URL is accepted, but this does not allow for proper Tooting functionality from Wavelog.

Environment:

    Wavelog Version: 1.8.2 
    Operating System: Debian Linux
    Browser: Firefox, Edge etc

Additional Information:

This issue prevents users from properly configuring their Mastodon accounts for full functionality within Wavelog.
![image](https://github.com/user-attachments/assets/2e8690a0-77ac-44db-92ee-86498df8d845)

**Comment by dg9vh** [comment]
Only unse mastodon.radio

VU2TUM ***@***.***> schrieb am Mi., 28. Aug. 2024, 15:45:
