### ISSUE TITLE
Could you rename the cron job from "Upload to lotw" to "sync with lotw"

### ISSUE THREAD

**Issue by Beiri22** [wavelog/wavelog#842]
Currently there is only a Cron Job "lotw_lotw_upload" that uploads QSOs to LoTW. Is there any Reason not also having one to download the QSOs; or, even better, one to sync bidirectionally?

**Comment by HB9HIL** [comment]
This is a mistake by us. The "LoTW Upload" does in fact a "Sync" -> Up- and Download

**Comment by Beiri22** [comment]
Oh, good. Have you thought of renaming it or rephrasing the description?

**Comment by HB9HIL** [comment]
Done with #844 :)

**Comment by Beiri22** [comment]
Thx :-)
