### ISSUE TITLE
Automatically set or at least verify ITU and CQ zone from Locator

### ISSUE THREAD

**Issue by Beiri22** [wavelog/wavelog#913]
Hi, 
I once came up with a similar request. Curently I do this manually with https://zone-check.eu/ -- maybe we could get to now, how they do it and include a similar functionality.

You could have a look at their scripts at first:
https://zone-check.eu/includes/locgrid.min.js
https://zone-check.eu/includes/zones.cq.js - there is some variable cqzones with i think google maps encoded paths.
https://zone-check.eu/includes/zones.itu.js -  there is some variable ituzones with i think google maps encoded paths.
https://zone-check.eu/includes/zones.min.js

maybe this could be an inspiration...

and sry to cause so much work.

**Comment by AndreasK79** [comment]
Hi,

It is an interesting thought, but it is only useful in the map.
I reproduced the feature locally:
![image](https://github.com/user-attachments/assets/c3720e4c-ae94-4307-b5e8-4ac8771d459c)

What it does, is that it uses the coordinates given from the map (on mouse move), and checks if those coordinates exists inside one of the zones, then returns the zone from there. The data from drawing the zones are used.

From what I understand, you want this in other parts of Wavelog?

**Comment by Beiri22** [comment]
Hi Andreas,

You could use it, when the callbook does not provide an ITU and/or CQ zone but a locator (when creating a log or pressing the get from callbook button later). Locator->Coord->ITU/CQ.

Also you could use it to find mismatching information in logs. I thought there was some search mismatching cq zone feature right now; which could also find mismatching itu zones...

**Comment by Beiri22** [comment]
Why manually? The checker could output results like a) wrong cq, b) missing cq, c) wrong itu, d) missing itu ... you make 4 buttons: Fill all missing (itu, cq), correct all wrong (itu, cq). e voila :-)

**Comment by AndreasK79** [comment]
Give me a data source with all the information I need, and I will fix that.

**Comment by AndreasK79** [comment]
You can probably determine the ITU zone from a grid, but what if the operation comes from a border (2 grids) or a corner (4 grids)? Which zone should we then take if that operation takes place from a border zone?

If we do not have the grid, it's a guessing game. Which ITU zone do you set in Canada, USA, Australia, China, Russia etc with multiple ITU zones?

**Comment by Beiri22** [comment]
What we could do is, **given a locator**:
No-Border-No-Corner-Case: Checking and autofill possible.
Border or Corner case: At least we could check, if the given ITU and CQ zones would match the border or corner. We cannot fill without guessing. We could however tell the user that there is another category like edge cases where multiple ITU / CQ-Zones would be possible.

**Comment by AndreasK79** [comment]
I quickly made an ITU zone checker by doing the same as I did with the CQ zone checker, and found that the data contained in the database was not complete, so the source needs to be updated to be able to determine which zones are wrong.
I quickly found that zone 1 and 4 are not set at all in the table, and would render Alaska and parts of Canada with a "wrong zone".

As for determining the edge cases, it is difficult to say. It all depends on your log, and probably what part of the world you are in.

I guess an ITU zone fixer would go like this (given that you have a complete list of DXCC and ITU zones):
1. Find zone by grid
2. Find by DXCC and take the default one (like we do with CQ zone).

**Comment by Beiri22** [comment]
> and found that the data contained in the database was not complete
Do you mean the zone-check scripts or what database do you refer to?

**Comment by AndreasK79** [comment]
The zone checker is based on a database table called dxcc_master. This table contains information about the dxcc.
We need this as a datasource to find incorrect zones.

**Comment by Beiri22** [comment]
So this is a database table of the current version of wavelog. Are the variables cqzones and ituzones of zone-check.eu complete?

**Comment by AndreasK79** [comment]
What do you mean? zone-check.eu uses longitude/latitude to find cq/itu zones. That is all well and good if we have a gridsquare, but it is not a database we can download and use.

**Comment by Beiri22** [comment]
It may not be a database, but couldnt we extract the polygon information and make it a database?

**Comment by AndreasK79** [comment]
We have that data. That is in use in the ITU award map and the advanced logbook map. Still, it would only be useful if you have a grid or longitude/latitude.

It is not useful for making an ITU zone checker. You need a list of all ITU zones for each DXCC to do that.

**Comment by Beiri22** [comment]
Everything I am talking about is for the case that **the log has a locator ** (from direct entry or callbook lookup).

**Comment by AndreasK79** [comment]
So all you wants is that in QSO entry when a grid is entered (manually/callbook), the CQ/ITU zones will be filled based on that?

**Comment by Beiri22** [comment]
That was my main point. Lots of people do not enter the ITU zone in their qrz-profile, so this field is empty half the time.

Side point would be checking the plausibility of locator and itu/cq (as additional feature of the cq checker)
