### ISSUE TITLE
Mode not always selected/shown in live-qso when using wavelog-gate

### ISSUE THREAD

**Issue by Nailcoding** [wavelog/wavelog#952]
When using wavelog-gate to get trx data in the live-qso area, the mode is very often not shown (empty) in the dropdown. While band works always, the mode does not work in more than 50% of the mode changes. It is shown correctly in wavelog-gate, but not in wavelog. This maybe also a wavelog-gate bug. 
Versions:
Wavelog: 1.8.2
Wavelog-gate: 1.0.16

**Comment by int2001** [comment]
Can u please share a screenshot?

**Comment by Nailcoding** [comment]
![2024-09-16 13_49_24-Clipboard](https://github.com/user-attachments/assets/c1a7d61c-cf4a-4df1-bc15-4954f607db6c)

**Comment by int2001** [comment]
thank u.
the screenshot from WLGate and the expected value is missing.

Could you pse provide the following Informations:
- Screenshot WLGate (Tab "Status")
- Information about your TRX
- Given Mode vom TRX which fails.

tu

**Comment by Nailcoding** [comment]
![image](https://github.com/user-attachments/assets/1f61931f-2697-42f0-a4f3-c2dc854e871c)

**Comment by Nailcoding** [comment]
![image](https://github.com/user-attachments/assets/474f26af-c617-4ff1-b7c9-e5add23f381c)

**Comment by Nailcoding** [comment]
![image](https://github.com/user-attachments/assets/cf34dbbc-3539-43ef-bd90-fe8053201210)

**Comment by int2001** [comment]
okay.
can you pse check if you've (accidently) deactivated the submodes for SSB (USB/LSB) at the Adminmenu?

go to the Menue with the gear-symbol, then to Modes and search for SSB (upper right).
The Submodes USB/LSB should not be deactivated. If they're activated, pse send a screenshot from that as well.

<img width="871" alt="image" src="https://github.com/user-attachments/assets/00ac795b-2c5c-469e-b0f4-2c9d024cc233">

**Comment by int2001** [comment]
One more: due to trafficsaving WLGate only updates Wavelog of you QSY (change the QRG with the VFO). So it may be, that a mode-change only isn't detected to sync.

That'd be a bug indeed.

**Comment by Nailcoding** [comment]
The deactivated submodes were the reason for the problem. I did not accidentally deactivate them. I did this to keep the dropdown list as short as possible. I always only enter SSB, not USB or LSB.
